language: cpp
sudo: required

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
      env: GCC_VERSION=4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.9
          - binutils
          - gfortran-4.9
          - libgmp-dev
          - libgmpxx4ldbl
          - libtool
          - autoconf
          - libopenblas-dev

    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
      env: GCC_VERSION=7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - binutils
          - gfortran-7
          - libgmp-dev
          - libgmpxx4ldbl
          - libtool
          - autoconf
          - libopenblas-dev

    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
      env: GCC_VERSION=8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-8
          - binutils
          - gfortran-8
          - libgmp-dev
          - libgmpxx4ldbl
          - libtool
          - autoconf
          - libopenblas-dev

    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   compiler: clang
    #   env: COMPILER=clang++
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       packages:
    #       - libgmp-dev
    #       - libgmpxx4ldbl
    #   before_install:
    #   - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
    #   - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    #   - sudo apt-get update -qq 
    #   - sudo apt-get install -qq -y clang-format-3.9

    - os: osx
      compiler: clang
      before_install:
      - brew update
      - brew uninstall automake && brew install automake
      - brew install autoconf libtool
#      - brew install homebrew/science/openblas

install:
  - export CC=${CC}${GCC_VERSION:+-${GCC_VERSION}}
  - echo "CC=${CC}"
  - export CXX=${CXX}${GCC_VERSION:+-${GCC_VERSION}}
  - echo "CXX=${CXX}"
  - export FC=${GCC_VERSION:+gfortran-${GCC_VERSION}}
  - echo "FC=${FC}"
  - gcc -march=native -Q --help=target


before_script:
  - git clone --depth 1 https://github.com/linbox-team/givaro.git && cd givaro && ./autogen.sh && make && sudo make install && cd ..
  - git clone --depth=1 https://github.com/xianyi/OpenBLAS.git  && cd OpenBLAS && make && sudo make PREFIX="/usr/local" install && cd ..
  - export LD_LIBRARY_PATH=/usr/local/lib
  - ./autogen.sh

script:
  - make
  - make check
  - make benchmarks
  - make examples
  - make tutorials
  - make dist

after_failure:
  - cat config.log

notifications:
  on_success: change
  on_failure: always
